image: 'kavatech/espocrm:5.6.14'


persistence:
  class: ''
  size: 28Gi

ingress:
  host: ''
  class: 'nginx'
  clusterIssuer: 'letsencrypt-prod'

mariadb:
  rbac:
    create: true
  db:
    user: 'espocrm'
    name: 'espocrm'
  replication:
    enabled: false
  master:
    persistence:
      enabled: true
      storageClass: ''
      size: 10Gi