kind: PersistentVolumeClaim
apiVersion: v1
metadata:
   name: data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "{{ .Values.persistence.class }}"
  resources:
    requests:
      storage: {{ .Values.persistence.size }}