apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: espocrm
  annotations:
    kubernetes.io/ingress.class: {{ .Values.ingress.class }}
    nginx.ingress.kubernetes.io/proxy-body-size: 128m
    certmanager.k8s.io/cluster-issuer: {{ .Values.ingress.clusterIssuer }}
spec:
  tls:
  - hosts:
    - {{ .Values.ingress.host }}
    secretName: espocrm-ing-secret
  rules:
  - host: {{ .Values.ingress.host }}
    http:
      paths:
      - path: /
        backend:
          serviceName: espocrm
          servicePort: 80


